const List<String> BOOK_LIST_IMG_URL_ARR = [
  "https://img.huxiucdn.com/article/cover/201812/07/084721455216.jpg?imageView2/1/w/400/h/225/|imageMogr2/strip/interlace/1/quality/85/format/jpg",
  "https://img.huxiucdn.com/article/cover/201907/01/123053984071.jpg?imageView2/1/w/400/h/225/|imageMogr2/strip/interlace/1/quality/85/format/jpg",
  "https://img.huxiucdn.com/article/cover/201907/01/121034837698.jpg?imageView2/1/w/400/h/225/|imageMogr2/strip/interlace/1/quality/85/format/jpg",
  "https://img.huxiucdn.com/article/cover/201907/01/115511134445.jpg?imageView2/1/w/400/h/225/|imageMogr2/strip/interlace/1/quality/85/format/jpg",
  "https://img.huxiucdn.com/article/cover/201907/01/113756189521.jpg?imageView2/1/w/400/h/225/|imageMogr2/strip/interlace/1/quality/85/format/jpg",
];

const String BOOK_LIST_JSON_STR = '''
{
    "err_code": 0,
    "error": "",
    "data": [
        {
            "title": "时间的礼物",
            "author": "[瑞典] 弗雷德里克·巴克曼",
            "time": "2019年1月1日",
            "image": "https://bookset.me/cover/s29951659.jpg",
            "douban_score": 7.5,
            "double_score_c_ount": 2786,
            "douban_link": "https://book.douban.com/subject/30390651/",
            "introduction": "【内容简介】世间的一切都有标价，除了时间，一秒就是一秒，谁都无法讨价还价。于是我总在出差，把生命中的每分每秒都贡献给工作，因为我坚信创造财富才是时间的正经归宿。45岁时，我成为一个有事业和资本的成功人士，但妻子和儿子离开了我。癌症将我送进医院，一周前，我认识了隔壁 病房的五岁女孩。她用蜡笔给椅子涂颜色，用牛奶盒做恐龙、给兔子玩偶讲故事，都是为了安慰妈妈和来看望她的人不要难过。死亡一天天临近，女孩却一如既往期待妈妈讲睡前故事，期待上学，期待着明年的生日会。她偷偷告诉我，穿白大褂的外星人会来治好她的病。她让我想起自己的儿子，以及那些我没有为他做的事情。死神要来带走女孩的那天晚上，我的心像被撕开了一个大口子，我向死神提出用我的命换女孩的命，但死神还要求抹去我在世间的一切痕迹。过去的45年，从父母的儿子，到儿子的父亲，我是如何度过的？一次对过往的清...",
            "download_link_epub": "http://download.bookset.me/d.php?f=2019/1/%5B瑞典%5D-弗雷德里克·巴克曼-时间的礼物-9787201142821.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2019/1/%5B瑞典%5D-弗雷德里克·巴克曼-时间的礼物-9787201142821.azw3",
            "download_link_mobi": "http://download.bookset.me/d.php?f=2019/1/%5B瑞典%5D-弗雷德里克·巴克曼-时间的礼物-9787201142821.mobi"
        },
        {
            "title": "屠夫十字镇",
            "author": "[美] 约翰·威廉斯",
            "time": "2016年7月1日",
            "image": "https://bookset.me/cover/s28712182.jpg",
            "douban_score": 8.4,
            "double_score_c_ount": 1881,
            "douban_link": "https://book.douban.com/subject/26765928/",
            "introduction": "◆《斯通纳》作者约翰•威廉斯另一绝佳作品。一部年轻人带着寻找美好、摆脱庸俗日常生活的冲动，去旷野探寻世界源头的小说。一个关于寻找与梦想，信念、信仰和仪式，生存与改变的故事。◆《屠夫十字镇》比《斯通纳》更想了解世界的真实。它们同是一个有关面对无意义事物的坚忍，有关天真所致失败的故事。与坚守信念的斯通纳不同，这是一个带着激情、对未知充满好奇的年轻人，渴望寻求真实的世界：他所相信的，不是爱默生和梭罗等人的信念，而是相信背后的看见——除了旷野与经历，没有什么比内心的冲动更真诚、更迷人。同时，他在某种意义上又与斯通纳相同，他们做到了自我的实现。也许，我们每个人身上都有这样的冲动、激情，也造就了如今的自己。◆对年轻人的心灵进行的深入思索。作者约翰•威廉斯说，当一个从哈佛辍学的年轻人，来到西部看到了自然，看到了旷野的真实面貌，对他来说，会发生什么呢？这就是小说...",
            "download_link_epub": "http://download.bookset.me/d.php?f=2016/7/%5B美%5D-约翰·威廉斯-屠夫十字镇-9787208137189.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2016/7/%5B美%5D-约翰·威廉斯-屠夫十字镇-9787208137189.azw3",
            "download_link_mobi": "http://download.bookset.me/d.php?f=2016/7/%5B美%5D-约翰·威廉斯-屠夫十字镇-9787208137189.mobi"
        },
        {
            "title": "我怎样毁了我的一生",
            "author": "[法] 贝尔当·桑帝尼 文",
            "time": "2011年1月1日",
            "image": "https://bookset.me/cover/s6380450.jpg",
            "douban_score": 8.4,
            "double_score_c_ount": 12569,
            "douban_link": "https://book.douban.com/subject/5366275/",
            "introduction": "一个男人言简意赅描写了自己的人生，长大之前他英俊、应有尽有、从不寂寞，堪称上帝的宠儿，长大之后他丑陋、贫穷、虚伪，过着谎话连篇和庸俗不堪的生活，他是怎样毁了自己的一生呢？成功和失败、幸福和悲哀，一段有如过山车般的人生。成功的标准是什么？怎样的人生又应该被定义为“失败”呢？一则简练而深刻的人生寓言。",
            "download_link_epub": "http://download.bookset.me/d.php?f=2011/1/%5B法%5D-贝尔当·桑帝尼-文-我怎样毁了我的一生-9787108035226.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2011/1/%5B法%5D-贝尔当·桑帝尼-文-我怎样毁了我的一生-9787108035226.mobi",
            "download_link_mobi": ""
        },
        {
            "title": "反套路",
            "author": "（美）大卫·迪萨沃",
            "time": "2019年4月19日",
            "image": "https://bookset.me/cover/s32297388.jpg",
            "douban_score": 8.5,
            "double_score_c_ount": 14,
            "douban_link": "https://book.douban.com/subject/33407293/",
            "introduction": "学点反套路，少走10年弯路。很多时候，大脑可能会成为我们的敌人。它会导致你陷入察觉不到的偏见、混乱和误区，容易被他人影响——也就是被“套路”，从而犯错。•很多时候，大脑会偷懒，不假思索地做出错误的决定。•你的记忆很容易就会被改变，一张照片就会让你想起很多根本不存在的事情。•在说话的过程中，比喻会以你想象不到的速度改变你对事物的看法。•遇到限时抢购的时候，明明自己并没有需求，却觉得不买就对不起自己。•手持一杯热饮，比一杯冷饮更容易产生亲和力；喝了一杯甜饮的人比喝白水的人更愿意原谅别人；算数学题时，拿着重物，更容易给出更高的估值。…………心理学家、跨界科学家大卫•迪萨沃为你揭示日常生活中存在的思维套路，用科学的方法帮你彻底掌控自己的人生！",
            "download_link_epub": "http://download.bookset.me/d.php?f=2019/4/（美）大卫·迪萨沃-反套路-9787559627452.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2019/4/（美）大卫·迪萨沃-反套路-9787559627452.azw3",
            "download_link_mobi": "http://download.bookset.me/d.php?f=2019/4/（美）大卫·迪萨沃-反套路-9787559627452.mobi"
        },
        {
            "title": "启示录",
            "author": "[美] Marty Cagan",
            "time": "2011年5月1日",
            "image": "https://bookset.me/cover/s6474670.jpg",
            "douban_score": 8.5,
            "double_score_c_ount": 5852,
            "douban_link": "https://book.douban.com/subject/5914587/",
            "introduction": "为什么市场上那么多软件产品无人问津，成功的产品凤毛麟角？怎样发掘有价值的产品？拿什么说服开发团队接受你的产品设计？如何将敏捷方法融入产品开发？过去二十多年，Marty Cagan作为高级产品经理人为多家一流企业工作过，包括惠普、网景、美国在线、eBay。他亲历了个人电脑 、互联网、 电子商务的起落沉浮。《启示录：打造用户喜爱的产品》从人员、流程、产品三个角度介绍了现代软件（互联网）产品管理的实践经验和理念。七印部落正在翻译作者的博客和授课视频，欢迎访问微博：http://weibo.com/7seals-“Marty无疑是eBay最出色的产品经理，他对eBay的影响至今仍在。”— Frerk-Malte FellereBay德国区常务董事-“Marty是产品管理的行家里手。这本书如醍醐灌顶，让我茅塞顿开。”— Judy Gibbons...",
            "download_link_epub": "http://download.bookset.me/d.php?f=2011/5/%5B美%5D-Marty-Cagan-启示录-9787560970189.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2011/5/%5B美%5D-Marty-Cagan-启示录-9787560970189.azw3",
            "download_link_mobi": "http://download.bookset.me/d.php?f=2011/5/%5B美%5D-Marty-Cagan-启示录-9787560970189.mobi"
        },
        {
            "title": "樱桃的滋味",
            "author": "[伊朗] 阿巴斯·基阿鲁斯达米",
            "time": "2017年9月1日",
            "image": "https://bookset.me/cover/s29529538.jpg",
            "douban_score": 9.3,
            "double_score_c_ount": 784,
            "douban_link": "https://book.douban.com/subject/27091427/",
            "introduction": "阿巴斯是伊朗新浪潮电影开创者、诗意电影大师，一生拍摄了22部电影，受到黑泽明、戈达尔等电影巨匠的一致推崇。1997年，阿巴斯凭借《樱桃的滋味》获得戛纳电影节金棕榈奖，之后《何处是我朋友家》《橄榄树下的情人》《随风而逝》等作品均获国际大奖。阿巴斯的电影，用镜头凝视平凡人世，纯粹、简朴的故事给人以*单纯的感动。影像风格简洁而富有诗意，洋溢着人文情怀与哲学思考。《樱桃的滋味》是阿巴斯一生导演历程的珍贵总结，详尽而深刻地呈现了阿巴斯的艺术观和人生观，是一部兼具实用价值与美学价值的电影沉思录。",
            "download_link_epub": "http://download.bookset.me/d.php?f=2017/9/%5B伊朗%5D-阿巴斯·基阿鲁斯达米-樱桃的滋味-9787508676982.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2017/9/%5B伊朗%5D-阿巴斯·基阿鲁斯达米-樱桃的滋味-9787508676982.azw3",
            "download_link_mobi": "http://download.bookset.me/d.php?f=2017/9/%5B伊朗%5D-阿巴斯·基阿鲁斯达米-樱桃的滋味-9787508676982.mobi"
        },
        {
            "title": "时间的礼物",
            "author": "[瑞典] 弗雷德里克·巴克曼",
            "time": "2019年1月1日",
            "image": "https://bookset.me/cover/s29951659.jpg",
            "douban_score": 7.5,
            "double_score_c_ount": 2786,
            "douban_link": "https://book.douban.com/subject/30390651/",
            "introduction": "【内容简介】世间的一切都有标价，除了时间，一秒就是一秒，谁都无法讨价还价。于是我总在出差，把生命中的每分每秒都贡献给工作，因为我坚信创造财富才是时间的正经归宿。45岁时，我成为一个有事业和资本的成功人士，但妻子和儿子离开了我。癌症将我送进医院，一周前，我认识了隔壁 病房的五岁女孩。她用蜡笔给椅子涂颜色，用牛奶盒做恐龙、给兔子玩偶讲故事，都是为了安慰妈妈和来看望她的人不要难过。死亡一天天临近，女孩却一如既往期待妈妈讲睡前故事，期待上学，期待着明年的生日会。她偷偷告诉我，穿白大褂的外星人会来治好她的病。她让我想起自己的儿子，以及那些我没有为他做的事情。死神要来带走女孩的那天晚上，我的心像被撕开了一个大口子，我向死神提出用我的命换女孩的命，但死神还要求抹去我在世间的一切痕迹。过去的45年，从父母的儿子，到儿子的父亲，我是如何度过的？一次对过往的清...",
            "download_link_epub": "http://download.bookset.me/d.php?f=2019/1/%5B瑞典%5D-弗雷德里克·巴克曼-时间的礼物-9787201142821.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2019/1/%5B瑞典%5D-弗雷德里克·巴克曼-时间的礼物-9787201142821.azw3",
            "download_link_mobi": "http://download.bookset.me/d.php?f=2019/1/%5B瑞典%5D-弗雷德里克·巴克曼-时间的礼物-9787201142821.mobi"
        },
        {
            "title": "屠夫十字镇",
            "author": "[美] 约翰·威廉斯",
            "time": "2016年7月1日",
            "image": "https://bookset.me/cover/s28712182.jpg",
            "douban_score": 8.4,
            "double_score_c_ount": 1881,
            "douban_link": "https://book.douban.com/subject/26765928/",
            "introduction": "◆《斯通纳》作者约翰•威廉斯另一绝佳作品。一部年轻人带着寻找美好、摆脱庸俗日常生活的冲动，去旷野探寻世界源头的小说。一个关于寻找与梦想，信念、信仰和仪式，生存与改变的故事。◆《屠夫十字镇》比《斯通纳》更想了解世界的真实。它们同是一个有关面对无意义事物的坚忍，有关天真所致失败的故事。与坚守信念的斯通纳不同，这是一个带着激情、对未知充满好奇的年轻人，渴望寻求真实的世界：他所相信的，不是爱默生和梭罗等人的信念，而是相信背后的看见——除了旷野与经历，没有什么比内心的冲动更真诚、更迷人。同时，他在某种意义上又与斯通纳相同，他们做到了自我的实现。也许，我们每个人身上都有这样的冲动、激情，也造就了如今的自己。◆对年轻人的心灵进行的深入思索。作者约翰•威廉斯说，当一个从哈佛辍学的年轻人，来到西部看到了自然，看到了旷野的真实面貌，对他来说，会发生什么呢？这就是小说...",
            "download_link_epub": "http://download.bookset.me/d.php?f=2016/7/%5B美%5D-约翰·威廉斯-屠夫十字镇-9787208137189.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2016/7/%5B美%5D-约翰·威廉斯-屠夫十字镇-9787208137189.azw3",
            "download_link_mobi": "http://download.bookset.me/d.php?f=2016/7/%5B美%5D-约翰·威廉斯-屠夫十字镇-9787208137189.mobi"
        },
        {
            "title": "我怎样毁了我的一生",
            "author": "[法] 贝尔当·桑帝尼 文",
            "time": "2011年1月1日",
            "image": "https://bookset.me/cover/s6380450.jpg",
            "douban_score": 8.4,
            "double_score_c_ount": 12569,
            "douban_link": "https://book.douban.com/subject/5366275/",
            "introduction": "一个男人言简意赅描写了自己的人生，长大之前他英俊、应有尽有、从不寂寞，堪称上帝的宠儿，长大之后他丑陋、贫穷、虚伪，过着谎话连篇和庸俗不堪的生活，他是怎样毁了自己的一生呢？成功和失败、幸福和悲哀，一段有如过山车般的人生。成功的标准是什么？怎样的人生又应该被定义为“失败”呢？一则简练而深刻的人生寓言。",
            "download_link_epub": "http://download.bookset.me/d.php?f=2011/1/%5B法%5D-贝尔当·桑帝尼-文-我怎样毁了我的一生-9787108035226.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2011/1/%5B法%5D-贝尔当·桑帝尼-文-我怎样毁了我的一生-9787108035226.mobi",
            "download_link_mobi": ""
        },
        {
            "title": "反套路",
            "author": "（美）大卫·迪萨沃",
            "time": "2019年4月19日",
            "image": "https://bookset.me/cover/s32297388.jpg",
            "douban_score": 8.5,
            "double_score_c_ount": 14,
            "douban_link": "https://book.douban.com/subject/33407293/",
            "introduction": "学点反套路，少走10年弯路。很多时候，大脑可能会成为我们的敌人。它会导致你陷入察觉不到的偏见、混乱和误区，容易被他人影响——也就是被“套路”，从而犯错。•很多时候，大脑会偷懒，不假思索地做出错误的决定。•你的记忆很容易就会被改变，一张照片就会让你想起很多根本不存在的事情。•在说话的过程中，比喻会以你想象不到的速度改变你对事物的看法。•遇到限时抢购的时候，明明自己并没有需求，却觉得不买就对不起自己。•手持一杯热饮，比一杯冷饮更容易产生亲和力；喝了一杯甜饮的人比喝白水的人更愿意原谅别人；算数学题时，拿着重物，更容易给出更高的估值。…………心理学家、跨界科学家大卫•迪萨沃为你揭示日常生活中存在的思维套路，用科学的方法帮你彻底掌控自己的人生！",
            "download_link_epub": "http://download.bookset.me/d.php?f=2019/4/（美）大卫·迪萨沃-反套路-9787559627452.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2019/4/（美）大卫·迪萨沃-反套路-9787559627452.azw3",
            "download_link_mobi": "http://download.bookset.me/d.php?f=2019/4/（美）大卫·迪萨沃-反套路-9787559627452.mobi"
        },
        {
            "title": "启示录",
            "author": "[美] Marty Cagan",
            "time": "2011年5月1日",
            "image": "https://bookset.me/cover/s6474670.jpg",
            "douban_score": 8.5,
            "double_score_c_ount": 5852,
            "douban_link": "https://book.douban.com/subject/5914587/",
            "introduction": "为什么市场上那么多软件产品无人问津，成功的产品凤毛麟角？怎样发掘有价值的产品？拿什么说服开发团队接受你的产品设计？如何将敏捷方法融入产品开发？过去二十多年，Marty Cagan作为高级产品经理人为多家一流企业工作过，包括惠普、网景、美国在线、eBay。他亲历了个人电脑 、互联网、 电子商务的起落沉浮。《启示录：打造用户喜爱的产品》从人员、流程、产品三个角度介绍了现代软件（互联网）产品管理的实践经验和理念。七印部落正在翻译作者的博客和授课视频，欢迎访问微博：http://weibo.com/7seals-“Marty无疑是eBay最出色的产品经理，他对eBay的影响至今仍在。”— Frerk-Malte FellereBay德国区常务董事-“Marty是产品管理的行家里手。这本书如醍醐灌顶，让我茅塞顿开。”— Judy Gibbons...",
            "download_link_epub": "http://download.bookset.me/d.php?f=2011/5/%5B美%5D-Marty-Cagan-启示录-9787560970189.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2011/5/%5B美%5D-Marty-Cagan-启示录-9787560970189.azw3",
            "download_link_mobi": "http://download.bookset.me/d.php?f=2011/5/%5B美%5D-Marty-Cagan-启示录-9787560970189.mobi"
        },
        {
            "title": "樱桃的滋味",
            "author": "[伊朗] 阿巴斯·基阿鲁斯达米",
            "time": "2017年9月1日",
            "image": "https://bookset.me/cover/s29529538.jpg",
            "douban_score": 9.3,
            "double_score_c_ount": 784,
            "douban_link": "https://book.douban.com/subject/27091427/",
            "introduction": "阿巴斯是伊朗新浪潮电影开创者、诗意电影大师，一生拍摄了22部电影，受到黑泽明、戈达尔等电影巨匠的一致推崇。1997年，阿巴斯凭借《樱桃的滋味》获得戛纳电影节金棕榈奖，之后《何处是我朋友家》《橄榄树下的情人》《随风而逝》等作品均获国际大奖。阿巴斯的电影，用镜头凝视平凡人世，纯粹、简朴的故事给人以*单纯的感动。影像风格简洁而富有诗意，洋溢着人文情怀与哲学思考。《樱桃的滋味》是阿巴斯一生导演历程的珍贵总结，详尽而深刻地呈现了阿巴斯的艺术观和人生观，是一部兼具实用价值与美学价值的电影沉思录。",
            "download_link_epub": "http://download.bookset.me/d.php?f=2017/9/%5B伊朗%5D-阿巴斯·基阿鲁斯达米-樱桃的滋味-9787508676982.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2017/9/%5B伊朗%5D-阿巴斯·基阿鲁斯达米-樱桃的滋味-9787508676982.azw3",
            "download_link_mobi": "http://download.bookset.me/d.php?f=2017/9/%5B伊朗%5D-阿巴斯·基阿鲁斯达米-樱桃的滋味-9787508676982.mobi"
        }
    ]
}
''';

const String BOOK_DETAIL_JSON_STR = '''{
    "err_code": 0,
    "error": "",
    "data": [
        {
            "title": "时间的礼物",
            "author": "[瑞典] 弗雷德里克·巴克曼",
            "time": "2019年1月1日",
            "image": "https://bookset.me/cover/s29951659.jpg",
            "douban_score": 7.5,
            "double_score_c_ount": 2786,
            "douban_link": "https://book.douban.com/subject/30390651/",
            "introduction": "【内容简介】世间的一切都有标价，除了时间，一秒就是一秒，谁都无法讨价还价。于是我总在出差，把生命中的每分每秒都贡献给工作，因为我坚信创造财富才是时间的正经归宿。45岁时，我成为一个有事业和资本的成功人士，但妻子和儿子离开了我。癌症将我送进医院，一周前，我认识了隔壁 病房的五岁女孩。她用蜡笔给椅子涂颜色，用牛奶盒做恐龙、给兔子玩偶讲故事，都是为了安慰妈妈和来看望她的人不要难过。死亡一天天临近，女孩却一如既往期待妈妈讲睡前故事，期待上学，期待着明年的生日会。她偷偷告诉我，穿白大褂的外星人会来治好她的病。她让我想起自己的儿子，以及那些我没有为他做的事情。死神要来带走女孩的那天晚上，我的心像被撕开了一个大口子，我向死神提出用我的命换女孩的命，但死神还要求抹去我在世间的一切痕迹。过去的45年，从父母的儿子，到儿子的父亲，我是如何度过的？一次对过往的清...",
            "download_link_epub": "http://download.bookset.me/d.php?f=2019/1/%5B瑞典%5D-弗雷德里克·巴克曼-时间的礼物-9787201142821.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2019/1/%5B瑞典%5D-弗雷德里克·巴克曼-时间的礼物-9787201142821.azw3",
            "download_link_mobi": "http://download.bookset.me/d.php?f=2019/1/%5B瑞典%5D-弗雷德里克·巴克曼-时间的礼物-9787201142821.mobi"
        },
        {
            "title": "屠夫十字镇",
            "author": "[美] 约翰·威廉斯",
            "time": "2016年7月1日",
            "image": "https://bookset.me/cover/s28712182.jpg",
            "douban_score": 8.4,
            "double_score_c_ount": 1881,
            "douban_link": "https://book.douban.com/subject/26765928/",
            "introduction": "◆《斯通纳》作者约翰•威廉斯另一绝佳作品。一部年轻人带着寻找美好、摆脱庸俗日常生活的冲动，去旷野探寻世界源头的小说。一个关于寻找与梦想，信念、信仰和仪式，生存与改变的故事。◆《屠夫十字镇》比《斯通纳》更想了解世界的真实。它们同是一个有关面对无意义事物的坚忍，有关天真所致失败的故事。与坚守信念的斯通纳不同，这是一个带着激情、对未知充满好奇的年轻人，渴望寻求真实的世界：他所相信的，不是爱默生和梭罗等人的信念，而是相信背后的看见——除了旷野与经历，没有什么比内心的冲动更真诚、更迷人。同时，他在某种意义上又与斯通纳相同，他们做到了自我的实现。也许，我们每个人身上都有这样的冲动、激情，也造就了如今的自己。◆对年轻人的心灵进行的深入思索。作者约翰•威廉斯说，当一个从哈佛辍学的年轻人，来到西部看到了自然，看到了旷野的真实面貌，对他来说，会发生什么呢？这就是小说...",
            "download_link_epub": "http://download.bookset.me/d.php?f=2016/7/%5B美%5D-约翰·威廉斯-屠夫十字镇-9787208137189.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2016/7/%5B美%5D-约翰·威廉斯-屠夫十字镇-9787208137189.azw3",
            "download_link_mobi": "http://download.bookset.me/d.php?f=2016/7/%5B美%5D-约翰·威廉斯-屠夫十字镇-9787208137189.mobi"
        },
        {
            "title": "我怎样毁了我的一生",
            "author": "[法] 贝尔当·桑帝尼 文",
            "time": "2011年1月1日",
            "image": "https://bookset.me/cover/s6380450.jpg",
            "douban_score": 8.4,
            "double_score_c_ount": 12569,
            "douban_link": "https://book.douban.com/subject/5366275/",
            "introduction": "一个男人言简意赅描写了自己的人生，长大之前他英俊、应有尽有、从不寂寞，堪称上帝的宠儿，长大之后他丑陋、贫穷、虚伪，过着谎话连篇和庸俗不堪的生活，他是怎样毁了自己的一生呢？成功和失败、幸福和悲哀，一段有如过山车般的人生。成功的标准是什么？怎样的人生又应该被定义为“失败”呢？一则简练而深刻的人生寓言。",
            "download_link_epub": "http://download.bookset.me/d.php?f=2011/1/%5B法%5D-贝尔当·桑帝尼-文-我怎样毁了我的一生-9787108035226.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2011/1/%5B法%5D-贝尔当·桑帝尼-文-我怎样毁了我的一生-9787108035226.mobi",
            "download_link_mobi": ""
        },
        {
            "title": "反套路",
            "author": "（美）大卫·迪萨沃",
            "time": "2019年4月19日",
            "image": "https://bookset.me/cover/s32297388.jpg",
            "douban_score": 8.5,
            "double_score_c_ount": 14,
            "douban_link": "https://book.douban.com/subject/33407293/",
            "introduction": "学点反套路，少走10年弯路。很多时候，大脑可能会成为我们的敌人。它会导致你陷入察觉不到的偏见、混乱和误区，容易被他人影响——也就是被“套路”，从而犯错。•很多时候，大脑会偷懒，不假思索地做出错误的决定。•你的记忆很容易就会被改变，一张照片就会让你想起很多根本不存在的事情。•在说话的过程中，比喻会以你想象不到的速度改变你对事物的看法。•遇到限时抢购的时候，明明自己并没有需求，却觉得不买就对不起自己。•手持一杯热饮，比一杯冷饮更容易产生亲和力；喝了一杯甜饮的人比喝白水的人更愿意原谅别人；算数学题时，拿着重物，更容易给出更高的估值。…………心理学家、跨界科学家大卫•迪萨沃为你揭示日常生活中存在的思维套路，用科学的方法帮你彻底掌控自己的人生！",
            "download_link_epub": "http://download.bookset.me/d.php?f=2019/4/（美）大卫·迪萨沃-反套路-9787559627452.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2019/4/（美）大卫·迪萨沃-反套路-9787559627452.azw3",
            "download_link_mobi": "http://download.bookset.me/d.php?f=2019/4/（美）大卫·迪萨沃-反套路-9787559627452.mobi"
        },
        {
            "title": "启示录",
            "author": "[美] Marty Cagan",
            "time": "2011年5月1日",
            "image": "https://bookset.me/cover/s6474670.jpg",
            "douban_score": 8.5,
            "double_score_c_ount": 5852,
            "douban_link": "https://book.douban.com/subject/5914587/",
            "introduction": "为什么市场上那么多软件产品无人问津，成功的产品凤毛麟角？怎样发掘有价值的产品？拿什么说服开发团队接受你的产品设计？如何将敏捷方法融入产品开发？过去二十多年，Marty Cagan作为高级产品经理人为多家一流企业工作过，包括惠普、网景、美国在线、eBay。他亲历了个人电脑 、互联网、 电子商务的起落沉浮。《启示录：打造用户喜爱的产品》从人员、流程、产品三个角度介绍了现代软件（互联网）产品管理的实践经验和理念。七印部落正在翻译作者的博客和授课视频，欢迎访问微博：http://weibo.com/7seals-“Marty无疑是eBay最出色的产品经理，他对eBay的影响至今仍在。”— Frerk-Malte FellereBay德国区常务董事-“Marty是产品管理的行家里手。这本书如醍醐灌顶，让我茅塞顿开。”— Judy Gibbons...",
            "download_link_epub": "http://download.bookset.me/d.php?f=2011/5/%5B美%5D-Marty-Cagan-启示录-9787560970189.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2011/5/%5B美%5D-Marty-Cagan-启示录-9787560970189.azw3",
            "download_link_mobi": "http://download.bookset.me/d.php?f=2011/5/%5B美%5D-Marty-Cagan-启示录-9787560970189.mobi"
        },
        {
            "title": "樱桃的滋味",
            "author": "[伊朗] 阿巴斯·基阿鲁斯达米",
            "time": "2017年9月1日",
            "image": "https://bookset.me/cover/s29529538.jpg",
            "douban_score": 9.3,
            "double_score_c_ount": 784,
            "douban_link": "https://book.douban.com/subject/27091427/",
            "introduction": "阿巴斯是伊朗新浪潮电影开创者、诗意电影大师，一生拍摄了22部电影，受到黑泽明、戈达尔等电影巨匠的一致推崇。1997年，阿巴斯凭借《樱桃的滋味》获得戛纳电影节金棕榈奖，之后《何处是我朋友家》《橄榄树下的情人》《随风而逝》等作品均获国际大奖。阿巴斯的电影，用镜头凝视平凡人世，纯粹、简朴的故事给人以*单纯的感动。影像风格简洁而富有诗意，洋溢着人文情怀与哲学思考。《樱桃的滋味》是阿巴斯一生导演历程的珍贵总结，详尽而深刻地呈现了阿巴斯的艺术观和人生观，是一部兼具实用价值与美学价值的电影沉思录。",
            "download_link_epub": "http://download.bookset.me/d.php?f=2017/9/%5B伊朗%5D-阿巴斯·基阿鲁斯达米-樱桃的滋味-9787508676982.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2017/9/%5B伊朗%5D-阿巴斯·基阿鲁斯达米-樱桃的滋味-9787508676982.azw3",
            "download_link_mobi": "http://download.bookset.me/d.php?f=2017/9/%5B伊朗%5D-阿巴斯·基阿鲁斯达米-樱桃的滋味-9787508676982.mobi"
        },
        {
            "title": "打字机上的缪斯",
            "author": "[英]杰西·波顿",
            "time": "2019年5月1日",
            "image": "https://bookset.me/cover/s32299374.jpg",
            "douban_score": 8.7,
            "double_score_c_ount": 60,
            "douban_link": "https://book.douban.com/subject/33402237/",
            "introduction": "►即使每天不被理解一百次，我也要做自己喜欢的事！ ◄-►►►内容简介◄◄◄1幅画，2封信，3个女人，跨越30年的梦想……热爱写作的奥黛尔，来到梦想中的伦敦，却只能做个卖鞋女孩。她的写作梦想，被现实搁浅了整整五年，直到她收到了一个女人的来信……时间倒转回到三十年前，天 赋异禀的奥利芙来到西班牙度假。她早已收到应该艺术学院的录取信，却没有告诉任何人。但正是在这里，奥利芙坚定了自己一生的梦想。一幅神秘画作，两封改变人生的信件，串联起她们跨越三十年的梦想，也让这三个女人的命运紧密联系在了一起。-►►►编辑推荐◄◄◄►感动30国读者的年度暖心大作《打字机上的缪斯》！►稳居英国图书销售总榜，仅英国销量两年已突破50万册！►《出版人周刊》《书单》《卫报》等28家重磅媒体暖心推荐！►《打字机上的缪斯》是英国《星期日泰晤士报》畅销书、《纽约时报...",
            "download_link_epub": "http://download.bookset.me/d.php?f=2019/5/%5B英%5D杰西·波顿-打字机上的缪斯-9787532171187.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2019/5/%5B英%5D杰西·波顿-打字机上的缪斯-9787532171187.azw3",
            "download_link_mobi": "http://download.bookset.me/d.php?f=2019/5/%5B英%5D杰西·波顿-打字机上的缪斯-9787532171187.mobi"
        },
        {
            "title": "时间旅行者的妻子",
            "author": "[美] 奥德丽·尼芬格",
            "time": "2007年4月1日",
            "image": "https://bookset.me/cover/s2375756.jpg",
            "douban_score": 8.1,
            "double_score_c_ount": 38382,
            "douban_link": "https://book.douban.com/subject/2056749/",
            "introduction": "相遇那年，她6岁，他36岁；结婚那年，她23岁，他31岁；离别后再度重逢时，她82岁，他43岁。相对于如此真实、强烈的感觉，时间，微不足道……亨利，一位年轻帅气、爱冒险的图书管理员，可是他有慢性时间错位症，会不知不觉地游离在时间之间。克莱尔，亨利的妻子，一位生活秩序很规律的艺术家。亨利以为他在28岁时第一次遇到他20岁的妻子克莱尔，而克莱尔却说：“我从小就认识你了”。和克莱尔结婚多年的亨利，却又突然发现自己回到了童年，遇见了他6岁的妻子。如果生命是一场旅行，亨利的旅程肯定比常人更迂回更深刻，那些不由自主地消失，不得不一再体验曾经遭受的经历，他只能旁观、重复品味着那些快乐、悲伤和痛苦。可是在时间的正常旅途中行走的克莱尔呢？她只能被亨利远远抛在了后面，渴望，焦急，等着爱人回到她的身边。她虽然拥有时间，却只能通过捉摸亨利来触摸时间。时间过滤...",
            "download_link_epub": "http://download.bookset.me/d.php?f=2007/4/%5B美%5D-奥德丽·尼芬格-时间旅行者的妻子-9787020060504.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2007/4/%5B美%5D-奥德丽·尼芬格-时间旅行者的妻子-9787020060504.azw3",
            "download_link_mobi": "http://download.bookset.me/d.php?f=2007/4/%5B美%5D-奥德丽·尼芬格-时间旅行者的妻子-9787020060504.mobi"
        },
        {
            "title": "单向度的人",
            "author": "(美)赫伯特·马尔库塞",
            "time": "2006年4月1日",
            "image": "https://bookset.me/cover/s1659154.jpg",
            "douban_score": 8.5,
            "double_score_c_ount": 2134,
            "douban_link": "https://book.douban.com/subject/1787729/",
            "introduction": "赫伯特·尔库塞（Herbert Marcuse，1898-1979）是法兰克福学派左翼主要代表人物，本书是其最负盛名的著作，旨在揭示当代发达工业社会型的极权主义特征。此书在英国和美国出版后，先后在德国和法国出德文版和法文版，其后又译成多种文字在许多国家出版，被称为西方6 0年代末大学造反运动的教科书.全书除导言外包括“单向度社会”、“单向度的思想”和“进行替代性选择的机会”三部分。作者通过对政治、生活、思想、文化、语言等领域的分析、批判，指出发达工业社会是如何成功地压制了人们内心中的否定性、批判性、超越性的向度，使这个社会成为单向度的社会，而生活于其中的人成了单向度的人，这种人丧失了自由和创造力，不再想像或追求与现实生活不同的另一种生活。本书对现代资本主义社会作了较为深刻的揭露和探索，但暴露出其社会批判理论的乌托邦性质。本书对研究兰克福学派和马尔库...",
            "download_link_epub": "http://download.bookset.me/d.php?f=2006/4/(美)赫伯特·马尔库塞-单向度的人-9787532739103.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2006/4/(美)赫伯特·马尔库塞-单向度的人-9787532739103.azw3",
            "download_link_mobi": "http://download.bookset.me/d.php?f=2006/4/(美)赫伯特·马尔库塞-单向度的人-9787532739103.mobi"
        },
        {
            "title": "事物的味道，我尝得太早了",
            "author": "[日] 石川啄木",
            "time": "2016年5月1日",
            "image": "https://bookset.me/cover/s28685720.jpg",
            "douban_score": 8.6,
            "double_score_c_ount": 3676,
            "douban_link": "https://book.douban.com/subject/26759579/",
            "introduction": "全书收录了石川啄木的四 部小集子。《一握砂》包含551首短歌，《可悲的玩具》包含194首短歌，这两部歌集诚恳地记录了诗人在贫病生活中的哀思和叹息。《叫子和口哨》为石川啄木创作的6首现代诗，着重在对现实世界的思考。《可以吃的诗》则是诗人针对诗歌创作而写的一篇自白文章，简述了自己的创作之路，剖析自己的心灵。",
            "download_link_epub": "http://download.bookset.me/d.php?f=2016/5/%5B日%5D-石川啄木-事物的味道，我尝得太早了-9787208136991.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2016/5/%5B日%5D-石川啄木-事物的味道，我尝得太早了-9787208136991.azw3",
            "download_link_mobi": "http://download.bookset.me/d.php?f=2016/5/%5B日%5D-石川啄木-事物的味道，我尝得太早了-9787208136991.mobi"
        },
        {
            "title": "美国陷阱",
            "author": "[法] 弗雷德里克·皮耶鲁齐",
            "time": "2019年5月1日",
            "image": "https://bookset.me/cover/s32305312.jpg",
            "douban_score": 8.6,
            "double_score_c_ount": 936,
            "douban_link": "https://book.douban.com/subject/33379779/",
            "introduction": "2013年4月14日，美国纽约肯尼迪国际机场，法国阿尔斯通集团锅炉部全球负责人弗雷德里克•皮耶鲁齐，刚下飞机就被美国联邦调查局探员逮捕。 这场抓捕不仅仅是针对他个人的行为，而是美国政府针对法国阿尔斯通的系列行动之一。之后，美国司法部指控皮耶鲁齐涉嫌商业贿赂，并对阿尔斯通处以7.72亿美元罚款。阿尔斯通的电力业务，最终被行业内的主要竞争对手——美国通用电气公司收购。阿尔斯通这家曾经横跨全球电力能源与轨道交通行业的商业巨头，因此被美国人“肢解”。而皮耶鲁齐直到2018年9月才走出监狱，恢复自由。 在《美国陷阱》一书中，皮耶鲁齐以身陷囹圄的亲身经历披露了阿尔斯通被美国企业“强制”收购，以及美国利用《反海外腐败法》打击美国企业竞争对手的内幕。 这是一场隐秘的经济战争。",
            "download_link_epub": "http://download.bookset.me/d.php?f=2019/5/%5B法%5D-弗雷德里克·皮耶鲁齐-美国陷阱-9787521702415.epub",
            "download_link_azw3": "http://download.bookset.me/d.php?f=2019/5/%5B法%5D-弗雷德里克·皮耶鲁齐-美国陷阱-9787521702415.azw3",
            "download_link_mobi": "http://download.bookset.me/d.php?f=2019/5/%5B法%5D-弗雷德里克·皮耶鲁齐-美国陷阱-9787521702415.mobi"
        }
    ]
}''';
