const TOAST_CHAPTER_IMAGE_JUMP_PREVIOUS_TOUCH = "再次滑动进入上一章。";
const TOAST_CHAPTER_IMAGE_JUMP_NEXT_TOUCH = "再次滑动进入下一章。";

const TOAST_CHAPTER_IMAGE_JUMP_PREVIOUS_CLICK = "再次点击进入上一章。";
const TOAST_CHAPTER_IMAGE_JUMP_NEXT_CLICK = "再次点击进入下一章。";
